// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{
    GUEST_CODE_FOR_ZK_PROOF_ELF, GUEST_CODE_FOR_ZK_PROOF_ID,
    GUEST_CODE_FOR_ADD_LIQUIDITY_ELF, GUEST_CODE_FOR_ADD_LIQUIDITY_ID,
    GUEST_CODE_FOR_REMOVE_LIQUIDITY_ELF, GUEST_CODE_FOR_REMOVE_LIQUIDITY_ID
};
use risc0_zkvm::{default_prover, ExecutorEnv};
use serde::{Deserialize, Serialize};
use serde_json::from_reader;
use sha3::{Digest, Keccak256};
use std::io;

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct SwapInputs {
    pub reserve_in: u128,
    pub reserve_out: u128,
    pub amount_in: u128,
    pub fee_numerator: u128,
    pub fee_denominator: u128,
    pub expected_out: u128,
    pub min_out: u128,
    pub max_slippage_bps: u128,   
    pub chain_id: u64,
    pub pool: [u8; 20],
    pub token_in: [u8; 20],
    pub to: [u8; 20],
    pub expiry: u64,
    pub nonce: u64,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct SwapJournal {
    pub chain_id: u64,
    pub pool: [u8; 20],
    pub token_in: [u8; 20],
    pub to: [u8; 20],
    pub expiry: u64,
    pub nonce: u64,
    pub reserve_in: u128,
    pub reserve_out: u128,
    pub amount_in: u128,
    pub fee_numerator: u128,
    pub fee_denominator: u128,
    pub expected_out: u128,
    pub min_out: u128,
    pub max_slippage_bps: u128,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct AddLiquidityInputs {
    pub reserve0: u128,
    pub reserve1: u128,
    pub amount0: u128,
    pub amount1: u128,
    pub total_supply: u128,
    pub is_first_add: bool,
    
      
    pub min_amount0: u128,          
    pub min_amount1: u128,          
    pub min_liquidity: u128,        
    
      
    pub fee_enabled: bool,
    pub fee_to: [u8; 20],
    pub last_k: u128,
    
      
    pub chain_id: u64,
    pub pool: [u8; 20],
    pub user: [u8; 20],
    pub expiry: u64,
    pub nonce: u64,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct RemoveLiquidityInputs {
    pub reserve0: u128,
    pub reserve1: u128,
    pub total_supply: u128,
    pub liquidity: u128,
    
      
    pub min_amount0_out: u128,      
    pub min_amount1_out: u128,      
    
      
    pub fee_enabled: bool,
    pub fee_to: [u8; 20],
    pub last_k: u128,
    
      
    pub chain_id: u64,
    pub pool: [u8; 20],
    pub user: [u8; 20],
    pub expiry: u64,
    pub nonce: u64,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct AddLiquidityJournal {
    pub chain_id: u64,
    pub pool: [u8; 20],
    pub user: [u8; 20],
    pub expiry: u64,
    pub nonce: u64,
    
      
    pub reserve0: u128,
    pub reserve1: u128,
    pub amount0: u128,
    pub amount1: u128,
    pub total_supply: u128,
    pub is_first_add: bool,
    pub liquidity_minted: u128,
    
      
    pub protocol_fee_lp: u128,    
    pub new_k: u128,              
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct RemoveLiquidityJournal {
    pub chain_id: u64,
    pub pool: [u8; 20],
    pub user: [u8; 20],
    pub expiry: u64,
    pub nonce: u64,
    
      
    pub reserve0: u128,
    pub reserve1: u128,
    pub total_supply: u128,
    pub liquidity: u128,
    pub amount0_out: u128,
    pub amount1_out: u128,
    
      
    pub protocol_fee_lp: u128,    
    pub new_k: u128,              
}

fn eip191_proof_hash(journal: &SwapJournal) -> [u8; 32] {
    // keccak256(abi.encodePacked(...)) 
    let mut bytes = Vec::new();
    bytes.extend_from_slice(&journal.chain_id.to_be_bytes());
    bytes.extend_from_slice(&journal.pool);
    bytes.extend_from_slice(&journal.token_in);
    bytes.extend_from_slice(&journal.to);
    bytes.extend_from_slice(&journal.expiry.to_be_bytes());
    bytes.extend_from_slice(&journal.nonce.to_be_bytes());
    bytes.extend_from_slice(&journal.reserve_in.to_be_bytes());
    bytes.extend_from_slice(&journal.reserve_out.to_be_bytes());
    bytes.extend_from_slice(&journal.amount_in.to_be_bytes());
    bytes.extend_from_slice(&journal.fee_numerator.to_be_bytes());
    bytes.extend_from_slice(&journal.fee_denominator.to_be_bytes());
    bytes.extend_from_slice(&journal.expected_out.to_be_bytes());
    bytes.extend_from_slice(&journal.min_out.to_be_bytes());
    bytes.extend_from_slice(&journal.max_slippage_bps.to_be_bytes());

    let mut keccak = Keccak256::new();
    keccak.update(&bytes);
    let hash = keccak.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&hash);
    out
}

fn eip191_add_liquidity_proof_hash(journal: &AddLiquidityJournal) -> [u8; 32] {
    // keccak256(abi.encodePacked(...)) 
    let mut bytes = Vec::new();
    bytes.extend_from_slice(&journal.chain_id.to_be_bytes());
    bytes.extend_from_slice(&journal.pool);
    bytes.extend_from_slice(&journal.user);
    bytes.extend_from_slice(&journal.expiry.to_be_bytes());
    bytes.extend_from_slice(&journal.nonce.to_be_bytes());
    bytes.extend_from_slice(&journal.reserve0.to_be_bytes());
    bytes.extend_from_slice(&journal.reserve1.to_be_bytes());
    bytes.extend_from_slice(&journal.amount0.to_be_bytes());
    bytes.extend_from_slice(&journal.amount1.to_be_bytes());
    bytes.extend_from_slice(&journal.total_supply.to_be_bytes());
    bytes.extend_from_slice(&journal.liquidity_minted.to_be_bytes());
    bytes.extend_from_slice(&journal.protocol_fee_lp.to_be_bytes());
    bytes.extend_from_slice(&journal.new_k.to_be_bytes());

    let mut keccak = Keccak256::new();
    keccak.update(&bytes);
    let hash = keccak.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&hash);
    out
}

fn eip191_remove_liquidity_proof_hash(journal: &RemoveLiquidityJournal) -> [u8; 32] {
    // keccak256(abi.encodePacked(...)) 
    let mut bytes = Vec::new();
    bytes.extend_from_slice(&journal.chain_id.to_be_bytes());
    bytes.extend_from_slice(&journal.pool);
    bytes.extend_from_slice(&journal.user);
    bytes.extend_from_slice(&journal.expiry.to_be_bytes());
    bytes.extend_from_slice(&journal.nonce.to_be_bytes());
    bytes.extend_from_slice(&journal.reserve0.to_be_bytes());
    bytes.extend_from_slice(&journal.reserve1.to_be_bytes());
    bytes.extend_from_slice(&journal.total_supply.to_be_bytes());
    bytes.extend_from_slice(&journal.liquidity.to_be_bytes());
    bytes.extend_from_slice(&journal.amount0_out.to_be_bytes());
    bytes.extend_from_slice(&journal.amount1_out.to_be_bytes());
    bytes.extend_from_slice(&journal.protocol_fee_lp.to_be_bytes());
    bytes.extend_from_slice(&journal.new_k.to_be_bytes());

    let mut keccak = Keccak256::new();
    keccak.update(&bytes);
    let hash = keccak.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&hash);
    out
}

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // An executor environment describes the configurations for the zkVM
    // including program inputs.
    // A default ExecutorEnv can be created like so:
    // `let env = ExecutorEnv::builder().build().unwrap();`
    // However, this `env` does not have any inputs.
    //
    // To add guest input to the executor environment, use
    // ExecutorEnvBuilder::write().
    // To access this method, you'll need to use ExecutorEnv::builder(), which
    // creates an ExecutorEnvBuilder. When you're done adding input, call
    // ExecutorEnvBuilder::build().

      
    let input_json: serde_json::Value = from_reader(io::stdin()).expect("invalid JSON on stdin");
    
      
    if input_json.get("liquidity").is_some() && input_json.get("amount0").is_none() {
          
        let input: RemoveLiquidityInputs = serde_json::from_value(input_json).expect("invalid JSON for RemoveLiquidityInputs");
        
        let env = ExecutorEnv::builder()
            .write(&input)
            .unwrap()
            .build()
            .unwrap();

        let prover = default_prover();
        let prove_info = prover
            .prove(env, GUEST_CODE_FOR_REMOVE_LIQUIDITY_ELF)
            .unwrap();

        let receipt = prove_info.receipt;
        let journal: RemoveLiquidityJournal = receipt.journal.decode().unwrap();

        let proof_hash = eip191_remove_liquidity_proof_hash(&journal);
        println!("proof_hash=0x{}", hex::encode(proof_hash));

        receipt
            .verify(GUEST_CODE_FOR_REMOVE_LIQUIDITY_ID)
            .unwrap();
    } else if input_json.get("amount0").is_some() && input_json.get("amount1").is_some() {
          
        let input: AddLiquidityInputs = serde_json::from_value(input_json).expect("invalid JSON for AddLiquidityInputs");
        
        let env = ExecutorEnv::builder()
            .write(&input)
            .unwrap()
            .build()
            .unwrap();

        let prover = default_prover();
        let prove_info = prover
            .prove(env, GUEST_CODE_FOR_ADD_LIQUIDITY_ELF)
            .unwrap();

        let receipt = prove_info.receipt;
        let journal: AddLiquidityJournal = receipt.journal.decode().unwrap();

        let proof_hash = eip191_add_liquidity_proof_hash(&journal);
        println!("proof_hash=0x{}", hex::encode(proof_hash));

        receipt
            .verify(GUEST_CODE_FOR_ADD_LIQUIDITY_ID)
            .unwrap();
    } else {
        // Swap
        let input: SwapInputs = serde_json::from_value(input_json).expect("invalid JSON for SwapInputs");

        let env = ExecutorEnv::builder()
            .write(&input)
            .unwrap()
            .build()
            .unwrap();

        let prover = default_prover();
        let prove_info = prover
            .prove(env, GUEST_CODE_FOR_ZK_PROOF_ELF)
            .unwrap();

        let receipt = prove_info.receipt;
        let journal: SwapJournal = receipt.journal.decode().unwrap();

        let proof_hash = eip191_proof_hash(&journal);
        println!("proof_hash=0x{}", hex::encode(proof_hash));

        receipt
            .verify(GUEST_CODE_FOR_ZK_PROOF_ID)
            .unwrap();
    }
}
